    <!-- footer -->
    <footer id='footer'>
        <p>
            <a href='http://processwire.com'><?php echo __('Powered by ProcessWire CMS'); ?></a>
        </p>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $config->urls->templates?>scripts/vendor/jquery-2.1.3.min.js">\x3C/script>')</script>

    <script src="<?php echo AIOM::JS(array('scripts/vendor/html5shiv.js','scripts/main.js')); ?>"></script>
</body>
</html>
